// Generated by dts-bundle-generator v9.5.1

export type ShortcutCallback = (event: KeyboardEvent) => void;
export type Shortcuts = Record<string, ShortcutCallback>;
declare function useShortcuts(keys: Shortcuts): void;

export { useShortcuts as default };

export {};
